name: Build on macOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Deps
        run: |
          brew update
          brew install libtool meson ninja pkg-config
      - name: Build
        run: |
          mkdir build
          cd build
          ../configure
